
INSERT INTO `texty` ( `slug`, `name`, `prompt`, `user_title`, `user_email_subject`, `user_email_content`, `user_sms`, `user2_title`, `user2_email_subject`, `user2_email_content`, `user2_sms`, `admin_email_subject`, `admin_email_content`, `admin_sms`, `flagstring`, `vars`, `flag`) VALUES

( 'ticketbox_view_save_support', 'تیکت پشتیبانی - ارسال پاسخ', '', 'ارسال‌کننده پیام', 'پیام پشتیبانی جدید #{ticket_id}', 'با سلام،\r\n\r\nکاربرا گرامی {user_name}، درخواست پشتیبانی شما به شناسه #{ticket_id} با موفقیت ثبت شد.\r\nلطفا منتظر دریافت پاسخ بمانید.\r\n\r\n{ticket_link}\r\n\r\nبا تشکر', 'با سلام\r\nتیکت شما به شناسه #{ticket_id} ثبت شد و در اولین فرصت پاسخ داده خواهد شد.', 'دریافت‌کننده پیام', 'پاسخ به پیام پشتیبانی #{ticket_id}', 'با سلام،\r\n\r\nکاربر گرامی {user_name}، درخواست پشتیبانی شما به شناسه #{ticket_id} پاسخ جدیدی داده شد.\r\n\r\n{ticket_link}\r\n\r\nبا تشکر', 'پاسخ جدید برای \"{ticket_name}\"', 'پیام پشتیبانی جدید توسط {user_name}', 'با سلام، \r\n\r\nتیکت جدید توسط {user_name} در دسته {ticket_cat} با عنوان {tickt_name} ثبت شده است.\r\n{ticket_adminlink}\r\n\r\nبا تشکر', 'پیام پشتیبانی جدید، توسط {user_name}\r\nعنوان پیام پشتیبانی : {ticket_name}', '0111111', 'ticket_id ticket_name ticket_cat ticket_link ticket_adminlink', 1),

( 'ticketbox_view_save_askFromSeller', 'سوال از فروشنده - ارسال پاسخ', '', 'خریدار', 'ارسال پیام به {receiver_user_name}', 'با سلام،  کاربر گرامی {user_name}،‌ \r\n\r\nپیام شما در مورد \"{item_name}\" به فروشنده مربوطه ارسال شده است.\r\nلطفا منتظر پاسخ وی بمانید. \r\nآدرس پیام :‌ {ticket_link} \r\nآیتم مربوطه : {item_link}\r\n\r\nبا تشکر', 'پیام شما در مورد {item_name} به فروشنده مربوطه ارسال شد.', 'فروشنده', 'پیام جدید از {sender_user_name} در مورد {item_name}', 'با سلام،\r\nکاربر عزیز {user_name}، \r\n\r\nشما پیامی از طرف {sender_user_name} در رابطه با {item_name} دریافت کرده اید.\r\nبرای مشاهده پیام :‌ \r\n{ticket_link}\r\n\r\nبا تشکر', 'پیام جدید از طرف {sender_user_name} در رابطه با {item_name}', '', '', '', '0111111', 'ticket_id ticket_name ticket_cat ticket_link ticket_adminlink sender_user_name receiver_user_name item_title item_id item_name item_link', 1),

( 'ticketbox_mg_saveNew', 'تیکت پشتیبانی - ثبت توسط مدیر', 'پیام پشتیبانی جدید با موفقیت برای {user_name} ارسال شد.', '', '', '', '', 'کاربر گیرنده پیام', 'پیام  پشتیبانی جدید', 'با سلام\r\nکاربر گرامی {user_name}، \r\nاز طرف مدیریت سایت پیامی جدید با عنوان \"{ticket_name}\" برای شما ارسال شده است.\r\nبرای مشاهده پیام از آدرس زیر اقدام نمائید.\r\n{ticket_link}\r\n\r\nبا تشکر', 'پیام پشتیبانی جدید برای شما {ticket_name}', '', '', '', '1001111', 'ticket_id ticket_name ticket_link', 1),

( 'ticketbox_user_saveNew', 'تیکت پشتیبانی - ثبت توسط کاربر', 'کاربر گرامی، پیام پشتیبانی شما ثبت شده و در اولین فرصت پاسخ داده خواهد شد.', 'کاربر ارسال‌کننده پیام', 'پیام پشتیبانی #{ticket_id}', 'با سلام،\r\nکاربر گرامی {user_name}، پیام پشتیبانی شما با عنوان \"{ticket_name}\" ثبت شده و درحال بررسی میباشد.\r\nلطفا منتظر پاسخ از طرف مسئولین سایت بمانید.\r\n\r\n{ticket_link}\r\n\r\nبا تشکر', 'پیام پشتیبانی شما با شناسه #{ticket_id} ثبت شد.', '', '', '', '', 'تیکت جدید', 'با سلام، \r\nپیام پشتیبانی جدید با عنوان \"{ticket_name}\" از طرف \"{user_name}\" ثبت شده است.\r\n{ticket_adminlink}\r\nبا تشکر', 'تیکت جدید از \"{user_name}\" با موضوع \"{ticket_name}\"', '', 'ticket_id ticket_name ticket_link ticket_adminlink receiver_user_name sender_user_name', 1),

( 'ticketbox_user_saveNew_to_client', 'پیام کاربر به کاربر - ثبت جدید', 'کاربر گرامی، پیام شما ثبت و به لیست پیام‌های \"{receiver_user_name}\" افزوده شد.', 'ارسال‌کننده پیام', 'ارسال پیام به {receiver_user_name}', 'با سلام، \r\nکاربر گرامی {user_name}،\r\n\r\nپیام جدید شما با عنوان \"{ticket_name}\" در لیست پیام های {receiver_user_name} قرار گرفت.\r\n\r\nبا تشکر', 'پیام جدید برای {receiver_user_name} ارسال شد.', 'دریافت‌کننده پیام', 'پیام جدید از {sender_user_name}', 'با سلام، \r\nکاربر گرامی {user_name}،\r\n\r\nبرای شما پیام جدیدی از طرف {sender_user_name} ، با عنوان \"{ticket_name}\" ارسال شده است.\r\nبرای مشاهده پیام به آدرس زیر مراجعه نمائید :\r\n{ticket_link}\r\n\r\nبا تشکر', 'پیام جدید از {sender_user_name}', '', '', '', '1111111', 'ticket_id ticket_name ticket_link ticket_adminlink receiver_user_name sender_user_name', 1),

( 'ticketbox_user_saveNew_askFromSeller', 'سوال از فروشنده - پیام جدید', 'پیام شما برای فروشنده \"{item_name}\" ارسال شد و شما پس از دریافت پاسخ مطلع خواهید شد.', 'خریدار', 'پیام به فروشنده \"{item_name}\"', 'با سلام\r\nکاربر گرامی {user_name}،\r\n\r\nپیام شما برای {receiver_user_name} بابت {item_title}\" {item_name}\" ارسال شد.\r\n\r\nبا تشکر', '', 'فروشنده', 'پیام جدید درمورد {item_title} {item_name}', 'با سلام\r\nکاربر گرامی {user_name}،\r\n\r\nشما پیام جدیدی از طرف {receiver_user_name} بابت {item_title}\" {item_name}\" دارید.\r\nلطفا برای مشاهده پیام :\r\n{ticket_link}\r\n\r\nبا تشکر', 'پیام جدید درمورد {item_name}', '', '', '', '1111111', 'ticket_id ticket_name ticket_link ticket_adminlink receiver_user_name sender_user_name item_title item_id item_name', 1),

( 'ticketbox_view_save_to_client', 'پیام کاربر به کاربر - ارسال پاسخ', '', 'ارسال‌کننده پیام', 'پاسخ به پیام \"{ticket_name}\"', 'با سلام، \r\nکاربر گرامی {user_name}،\r\n\r\nپاسخ شما به پیام \"{ticket_name}\" به \"{receiver_user_name}\" ارسال شد.\r\n\r\nبا تشکر', '', 'دریافت‌کننده پیام', 'پاسخ به پیام \"{ticket_name}\"', 'با سلام،\r\nکاربر گرامی {user_name}،\r\n\r\nپاسخ جدیدی برای پیام \"{ticket_name}\" توسط {sender_user_name} ثبت شده است.\r\nبرای مشاهده :\r\n{ticket_link}\r\n\r\nبا تشکر', 'دریافت پاسخ جدید برای \"{ticket_name}\" از \"{sender_user_name}\"', '', '', '', '0111111', 'ticket_id ticket_name ticket_cat ticket_link ticket_adminlink sender_user_name receiver_user_name', 1);




--spi--
